// flow-typed signature: 5ef7f1c4eef40b5d18181fb8cd685e2a
// flow-typed version: <<STUB>>/react-blockies_v^1.4.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-blockies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-blockies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-blockies/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-blockies/dist/main.js' {
  declare module.exports: $Exports<'react-blockies/dist/main'>;
}
